### ISSUE TITLE
wrapped around link is truncated

### ISSUE THREAD

**Issue by thornedlove** [patrick96/click-link#8]
When wrap around is on,  a very long link will be truncated.

Ex:  
    https://github.com/patrick96/cli↩
ck-link

points to : https://github.com/patrick96/cli   
instead of: https://github.com/patrick96/click-link

**Comment by patrick96** [comment]
Unfortunately there is now way to differentiate between a soft wrapped link and two links on two separate lines. In the DOM they both look like two seperate lines with links on them.

So looking for the rest of the link on the next or previous lines may yield a totally separate link which is not desirable.

I will look into a few alternatives but since [language-hyperlink](https://atom.io/packages/language-hyperlink) only adds some classes to the link elements, I don't think there is a way to do this without completely rewriting the package and implementing the language-hyperlink functionality in here.

For now I'll leave this open, but if I don't find anything, I'll mark it 'wontfix'

**Comment by thornedlove** [comment]
I know programmers have it tough sometimes. 

Thanks for all the efforts.

**Comment by patrick96** [comment]
There does not seem to be a good solution for this except for turning off soft-wrapping.

**Comment by hollowdoor** [comment]
It appears that the link is a real link. Why don't you get the link by selection instead of actually making a link? You could then send the link to the system instead of relying on an html link.

**Comment by patrick96** [comment]
The links inside an atom buffer are not "real" links (`<a>` elements), they are just text that have been formatted to look this way.
What do you mean by "get the link by selection"?

**Comment by hollowdoor** [comment]
I didn't know that about them not being real links.

What I meant by get the link by selection is have an option where the user has to have the cursor in the link. Once the cursor is in the link if they `ctrl+click` then click-link tests around that cursor position for a link. Then open the found link. I'm assuming atom uses the same selection mechanism as a browser where you can programmatically move the selection around.

Or click-link could just require the entire url be selected for a wrapped text to work as a link. When the url fits, or wrapping is turned off it would work as usual.

Just some suggestions.
